# Generated by Django 5.1.7 on 2025-06-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('description', models.TextField(verbose_name='Описание')),
                ('main_attraction', models.CharField(max_length=200, verbose_name='Главная достопримечательность')),
                ('best_time_to_visit', models.CharField(max_length=100, verbose_name='Лучшее время для посещения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cities/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
    ]
