# Generated by Django 5.1.7 on 2025-06-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_city_latitude_city_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='city',
            name='longitude',
        ),
    ]
